x-healthcheck: &healthcheck
  interval: 30s
  timeout: 10s
  retries: 10
   
x-fake-healthcheck: &fake-healthcheck
  test: ["CMD", "true"]
  interval: 30s
  timeout: 10s
  retries: 3


services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "true"]
      <<: *healthcheck    
    entrypoint: /bin/sh -c
    depends_on:
      - gateway
    command: >
      "trap exit TERM;
       while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"
    restart: always
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.certbotrenew.schedule: "@every 10m"
      ofelia.job-exec.certbotrenew.command: >
        sh -c "
          if [ ! -f /etc/letsencrypt/initialized ]; then 
            rm -rf /etc/letsencrypt/live/nge &&\
            certbot certonly --webroot -w /var/www/certbot ${CERTBOT_DOMAINS} --non-interactive --cert-name nge --email ${TEAM_EMAIL} --agree-tos --no-eff-email &&\
            echo 1 > /etc/letsencrypt/initialized &&\
            echo 1 > /etc/letsencrypt/renewed ;\
          fi
        "

  gateway:
    image: nginx:stable-alpine
    container_name: gateway
    volumes:
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/nginx:/etc/nginx:ro
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: >
        (curl -sS http://127.0.0.1:80/health | grep UP &&
        curl -sS http://uptime.frk.wf/api/push/${GATEWAY_UPTIME_KEY}?status=up\&msg=OK) ||
        (curl -sS http://uptime.frk.wf/api/push/${GATEWAY_UPTIME_KEY}?status=down\&msg=FAILED && exit 1)
      <<: *healthcheck
    restart: always
    networks:
      - gateway
 
  nostr:
    image: ghcr.io/hoytech/strfry:latest
    container_name: nostr
    restart: always
    depends_on:
      - gateway
    volumes:
      - ./docker/nostr/strfry.conf:/etc/strfry.conf:ro
      - /srv/nostr/data:/app/strfry-db
    networks:
      nostr:
        aliases:
          - nostr.docker
      gateway:
        aliases:
          - nostr.docker
    healthcheck:
      test: ["CMD", "true"]
      <<: *healthcheck    


  
  gateway-refresher:
    image: ubuntu:latest
    container_name: gateway-refresher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/certbot/conf:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "true"]
      <<: *healthcheck
    command: >
      bash -c "
        apt-get update -qq && \
        apt-get install  -y ca-certificates curl &&\
        install -m 0755 -d /etc/apt/keyrings &&\
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc &&\
        chmod a+r /etc/apt/keyrings/docker.asc &&\
        echo \"deb [arch=\$$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \$$(. /etc/os-release && echo \$${VERSION_CODENAME}) stable\" | tee /etc/apt/sources.list.d/docker.list > /dev/null && apt-get update -qq && \
        apt-get update -qq && \
        apt-get install -y -qq docker-ce-cli && \
        while true; do
          sleep 600
        done
      "
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.gatewayrefresh.schedule: "@every 5m"
      ofelia.job-exec.gatewayrefresh.command: >
        bash -c "
          watched_containers=\$$(docker network inspect \"gateway\" --format '{{range .Containers}}{{.Name}} {{end}}') && \
          for container in \$${watched_containers}; do
            if [ \"\$${container}\" == \"gateway\" ]; then
                continue
            fi
            state=\$$(docker inspect --format='{{.State.Restarting}}' \"\$${container}\" 2>/dev/null)
            if [ \"\$${state}\" == \"true\" ]; then
                echo \"Detected restart of \$${container}. Restarting gateway...\"
                docker restart gateway
            fi
          done
          if [ -f /etc/letsencrypt/renewed ]; then
            echo \"Detected renewed certificates. Restarting gateway...\"
            docker restart gateway
            rm -f /etc/letsencrypt/renewed
          fi
        "
      ofelia.job-exec.gatewaymonthlyreload.schedule: "@monthly"
      ofelia.job-exec.gatewaymonthlyreload.command: >
        bash -c "
          docker exec gateway nginx -s reload
        "

  # website:
  #   build:
  #     context: .
  #   container_name: homepage
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "true"]
  #     <<: *healthcheck
  #   networks:
  #     - gateway    

  cron:
    container_name: cron
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Restart ofelia as soon as new containers come online
  # This is a workaround to ofelia not being able to reload the cron jobs at runtime
  cron-live:
    build:
      context: ./docker/ofelia-live
    container_name: cron-live
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro      
    depends_on:
      - cron

networks:
  gateway:
    driver: bridge
    name: gateway
  nostr:
    driver: bridge
    name: nostr
  